project:
  type: website

website:
  title: "EpiVerse"
  cookie-consent:
    type: express
  navbar:
    left:
      - repo.qmd
      - text: "Contributors"
        href: contributor.qmd
      - models.qmd
    right:
      - icon: "github"
        menu:
          - text: Feedback
            url: https://github.com/ropensci-review-tools/orgmetrics/discussions
          - text: Source Code
            url: https://github.com/ropensci-review-tools/orgmetrics
          - text: github.com/reconhub
            url: https://github.com/reconhub
          - text: github.com/epiverse-trace
            url: https://github.com/epiverse-trace
          - text: github.com/reconverse
            url: https://github.com/reconverse

format:
  html:
    page-layout: full
    theme: yeti
    css: styles.css
    toc: true
